version: '3.8'

services:
  django-crud-pg-service:
    image: postgres:16.2
    container_name: django_crud_postgres
    networks:
      - django-fastapi-crud-local
    ports:
      - "5556:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_crud
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  django-crud-service:
    image: django-crud
    container_name: django_crud
    command: bash /app/startup.sh
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_CODE_PATH: django_example
    networks:
      - django-fastapi-crud-local
    depends_on:
      - django-crud-pg-service
    links:
      - django-crud-pg-service:postgres_db
    volumes:
      - ./django_example:/app
    ports:
      - "8080:8080"

  fastapi-crud-pg-service:
    image: postgres:16.2
    container_name: fastapi_crud_postgres
    networks:
      - django-fastapi-crud-local
    ports:
      - "5557:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_crud
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  fastapi-crud-service:
    image: fastapi-crud
    container_name: fastapi_crud
    command: bash /app/startup.sh
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_CODE_PATH: fastapi_example
    networks:
      - django-fastapi-crud-local
    depends_on:
      - fastapi-crud-pg-service
    links:
      - fastapi-crud-pg-service:postgres_db
    volumes:
      - ./fastapi_example:/app
    ports:
      - "8000:8000"

networks:
  django-fastapi-crud-local:
