"""add tags

Revision ID: 407b70a35999
Revises: f0aba27820ec
Create Date: 2024-06-24 09:57:47.165644

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "407b70a35999"
down_revision: Union[str, None] = "f0aba27820ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fastapi_tag",
        sa.Column(
            "tag_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="unique identifier of the tag",
        ),
        sa.Column("tag_name", sa.String(length=70), nullable=False, comment="the name of the tag"),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
            comment="the date time in UTC, when the tag was created",
        ),
        sa.PrimaryKeyConstraint("tag_id"),
        sa.UniqueConstraint("tag_name"),
        comment="general information about article tags",
    )
    op.create_index(op.f("ix_fastapi_tag_tag_id"), "fastapi_tag", ["tag_id"], unique=False)
    op.create_table(
        "fastapi_article_tags",
        sa.Column("article_id", sa.UUID(), nullable=False, comment="the id of the article"),
        sa.Column("tag_id", sa.UUID(), nullable=False, comment="the id of the tag"),
        sa.ForeignKeyConstraint(["article_id"], ["fastapi_article.article_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["fastapi_tag.tag_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "tag_id"),
        comment="association table between article and tag",
    )
    op.alter_column(
        "fastapi_article",
        "article_name",
        existing_type=sa.VARCHAR(),
        comment="the name of the article",
        existing_comment="the content of the article",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fastapi_article",
        "article_name",
        existing_type=sa.VARCHAR(),
        comment="the content of the article",
        existing_comment="the name of the article",
        existing_nullable=False,
    )
    op.drop_table("fastapi_article_tags")
    op.drop_index(op.f("ix_fastapi_tag_tag_id"), table_name="fastapi_tag")
    op.drop_table("fastapi_tag")
    # ### end Alembic commands ###
