"""initial

Revision ID: ab1bfe48ad14
Revises:
Create Date: 2024-04-24 08:40:57.738714

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab1bfe48ad14"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fastapi_writer",
        sa.Column(
            "writer_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="unique identifier of the writer",
        ),
        sa.Column("first_name", sa.String(), nullable=True, comment="the first name of the writer"),
        sa.Column("last_name", sa.String(), nullable=True, comment="the last name of the writer"),
        sa.Column("email", sa.String(), nullable=False, comment="the email of the writer"),
        sa.Column("about", sa.String(), nullable=True, comment="a short intro of the writer"),
        sa.Column(
            "joined_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
            comment="the date time in UTC, when the writer joined",
        ),
        sa.PrimaryKeyConstraint("writer_id"),
        sa.UniqueConstraint("email"),
        comment="general information about writers",
    )
    op.create_index(op.f("ix_fastapi_writer_writer_id"), "fastapi_writer", ["writer_id"], unique=False)
    op.create_table(
        "fastapi_partner_program",
        sa.Column("writer_id", sa.UUID(), nullable=False, comment="unique identifier of the writer"),
        sa.Column(
            "joined_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("statement_timestamp()"),
            nullable=False,
            comment="the date time in UTC, when the writer joined the partner program",
        ),
        sa.Column(
            "payment_method",
            sa.String(),
            nullable=False,
            comment="the payment method of the partner program, eg: stripe",
        ),
        sa.Column("country_code", sa.String(), nullable=False, comment="the country iso code of the writer"),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="true if the partner program is active",
        ),
        sa.ForeignKeyConstraint(["writer_id"], ["fastapi_writer.writer_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("writer_id"),
        comment="information about partner program at writer level",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fastapi_partner_program")
    op.drop_index(op.f("ix_fastapi_writer_writer_id"), table_name="fastapi_writer")
    op.drop_table("fastapi_writer")
    # ### end Alembic commands ###
