# Generated by Django 5.0.4 on 2024-04-24 17:02

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "writer_id",
                    models.UUIDField(
                        db_comment="unique identifier of the writer",
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(db_comment="the first name of the writer", null=True)),
                ("last_name", models.CharField(db_comment="the last name of the writer", null=True)),
                ("email", models.EmailField(db_comment="the email of the writer", max_length=254, unique=True)),
                ("about", models.CharField(db_comment="a short intro of the writer", null=True)),
                (
                    "joined_timestamp",
                    models.DateTimeField(
                        db_comment="the date time in UTC, when the writer joined",
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
            ],
            options={
                "db_table": "django_writer",
                "db_table_comment": "general information about writers",
            },
        ),
        migrations.CreateModel(
            name="WriterPartnerProgram",
            fields=[
                (
                    "writer",
                    models.OneToOneField(
                        db_comment="unique identifier of the writer",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="partner_program",
                        serialize=False,
                        to="writers.writer",
                    ),
                ),
                (
                    "joined_timestamp",
                    models.DateTimeField(
                        db_comment="the date time in UTC, when the writer joined the partner program",
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("payment_method", models.CharField(db_comment="the payment method of the partner program")),
                ("country_code", models.CharField(db_comment="the country iso code of the writer")),
                ("active", models.BooleanField(db_comment="true if the partner program is active", db_default=True)),
            ],
            options={
                "db_table": "django_partner_program",
                "db_table_comment": "information about partner program at writer level",
            },
        ),
    ]
