# Generated by Django 5.0.4 on 2024-06-24 08:05

import django.contrib.postgres.functions
import django.db.models.functions.datetime
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "tag_id",
                    models.UUIDField(
                        db_comment="unique identifier of the tag",
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag_name", models.CharField(db_comment="the name of the tag", max_length=70, unique=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        db_comment="the date time in UTC, when the tag was created",
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
            ],
            options={
                "db_table": "django_tag",
                "db_table_comment": "general information about article tags",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(db_table="django_article_tags", related_name="tags", to="articles.tag"),
        ),
    ]
